" Name:         Gruvbox Material Hard
" Description:  Gruvbox with Material Palette
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/gruvbox-material/
" License:      MIT && Anti-996
" Last Updated: Tue 20 Aug 2019 08:52:59 AM CST

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'gruvbox-material-hard'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

let s:italics = !(get(g:, 'gruvbox_material_kill_italic', 0) && s:italics)
hi! link markdownH5 Yellow
hi! link markdownH6 Yellow
hi! link markdownCode Green
hi! link markdownCodeBlock Aqua
hi! link markdownCodeDelimiter Aqua
hi! link markdownBlockquote Grey
hi! link markdownListMarker Red
hi! link markdownOrderedListMarker Grey
hi! link markdownRule Grey
hi! link markdownHeadingRule Grey
hi! link markdownUrlDelimiter Grey
hi! link markdownLinkDelimiter Grey
hi! link markdownLinkTextDelimiter Grey
hi! link markdownHeadingDelimiter Orange
hi! link markdownLinkText Aqua
hi! link markdownUrlTitleDelimiter Green
hi! link markdownIdDeclaration markdownLinkText
hi! link markdownBoldDelimiter Grey
hi! link mkdBold Grey
hi! link mkdLink Aqua
hi! link mkdCodeDelimiter Aqua
hi! link mkdHeading Orange
hi! link mkdListItem Red
hi! link mkdDelimiter Grey
hi! link mkdId Yellow
hi! link htmlTagName Blue
hi! link htmlArg Orange
hi! link htmlScriptTag Purple
hi! link htmlSpecialTagName Blue
hi! link htmlSpecialChar Red
hi! link htmlTagN White
hi! link htmlTag AquaBold
hi! link htmlEndTag AquaBold
hi! link xmlEqual Blue
hi! link xmlDocTypeDecl Grey
hi! link xmlDocTypeKeyword Purple
hi! link xmlCdataStart Grey
hi! link xmlCdataCdata Purple
hi! link dtdFunction Grey
hi! link dtdTagName Purple
hi! link xmlAttrib Orange
hi! link xmlProcessingDelim Grey
hi! link dtdParamEntityPunct Grey
hi! link dtdParamEntityDPunct Grey
hi! link xmlAttribPunct Grey
hi! link xmlEntity Red
hi! link xmlEntityPunct Red
hi! link xmlTag AquaBold
hi! link xmlEndTag AquaBold
hi! link xmlTagName AquaBold
hi! link docbkKeyword AquaBold
hi! link cOperator Purple
hi! link cppOperator Purple
hi! link cStructure Orange
hi! link objcTypeModifier Red
hi! link objcDirective Blue
hi! link pythonBuiltin Orange
hi! link pythonBuiltinObj Orange
hi! link pythonBuiltinFunc Orange
hi! link pythonFunction Aqua
hi! link pythonDecorator Red
hi! link pythonInclude Blue
hi! link pythonImport Blue
hi! link pythonRun Blue
hi! link pythonCoding Blue
hi! link pythonOperator Orange
hi! link pythonException Red
hi! link pythonExceptions Purple
hi! link pythonBoolean Purple
hi! link pythonConditional Red
hi! link pythonRepeat Red
hi! link pythonDottedName GreenBold
hi! link pythonDot Grey
hi! link cssBraces White
hi! link cssFunctionName Yellow
hi! link cssIdentifier Orange
hi! link cssClassName Green
hi! link cssColor Blue
hi! link cssSelectorOp Blue
hi! link cssSelectorOp2 Blue
hi! link cssImportant Green
hi! link cssTextProp Aqua
hi! link cssAnimationProp Aqua
hi! link cssUIProp Yellow
hi! link cssTransformProp Aqua
hi! link cssTransitionProp Aqua
hi! link cssPrintProp Aqua
hi! link cssPositioningProp Yellow
hi! link cssBoxProp Aqua
hi! link cssFontDescriptorProp Aqua
hi! link cssFlexibleBoxProp Aqua
hi! link cssBorderOutlineProp Aqua
hi! link cssBackgroundProp Aqua
hi! link cssMarginProp Aqua
hi! link cssListProp Aqua
hi! link cssTableProp Aqua
hi! link cssFontProp Aqua
hi! link cssPaddingProp Aqua
hi! link cssDimensionProp Aqua
hi! link cssRenderProp Aqua
hi! link cssColorProp Aqua
hi! link cssGeneratedContentProp Aqua
hi! link cssVendor White
hi! link javaScriptFunction Aqua
hi! link javaScriptIdentifier Red
hi! link javaScriptMember Blue
hi! link javaScriptNumber Purple
hi! link javaScriptNull Purple
hi! link javaScriptParens White
hi! link javaScriptBraces White
hi! link javascriptImport Aqua
hi! link javascriptExport Aqua
hi! link javascriptClassKeyword Aqua
hi! link javascriptClassExtends Aqua
hi! link javascriptDefault Aqua
hi! link javascriptClassName Yellow
hi! link javascriptClassSuperName Yellow
hi! link javascriptGlobal Yellow
hi! link javascriptEndColons White
hi! link javascriptFuncArg White
hi! link javascriptGlobalMethod White
hi! link javascriptNodeGlobal White
hi! link javascriptBOMWindowProp White
hi! link javascriptArrayMethod White
hi! link javascriptArrayStaticMethod White
hi! link javascriptCacheMethod White
hi! link javascriptDateMethod White
hi! link javascriptMathStaticMethod White
hi! link javascriptURLUtilsProp White
hi! link javascriptBOMNavigatorProp White
hi! link javascriptDOMDocMethod White
hi! link javascriptDOMDocProp White
hi! link javascriptBOMLocationMethod White
hi! link javascriptBOMWindowMethod White
hi! link javascriptStringMethod White
hi! link javascriptVariable Orange
hi! link javascriptIdentifier Orange
hi! link javascriptClassSuper Orange
hi! link javascriptFuncKeyword Aqua
hi! link javascriptAsyncFunc Aqua
hi! link javascriptClassStatic Orange
hi! link javascriptOperator Red
hi! link javascriptForOperator Red
hi! link javascriptYield Red
hi! link javascriptExceptions Red
hi! link javascriptMessage Red
hi! link javascriptTemplateSB Aqua
hi! link javascriptTemplateSubstitution White
hi! link javascriptLabel White
hi! link javascriptObjectLabel White
hi! link javascriptPropertyName White
hi! link javascriptLogicSymbols Purple
hi! link javascriptArrowFunc Yellow
hi! link javascriptDocParamName LightGrey
hi! link javascriptDocTags LightGrey
hi! link javascriptDocNotation LightGrey
hi! link javascriptDocParamType LightGrey
hi! link javascriptDocNamedParamType LightGrey
hi! link javascriptBrackets White
hi! link javascriptDOMElemAttrs White
hi! link javascriptDOMEventMethod White
hi! link javascriptDOMNodeMethod White
hi! link javascriptDOMStorageMethod White
hi! link javascriptHeadersMethod White
hi! link javascriptAsyncFuncKeyword Red
hi! link javascriptAwaitFuncKeyword Red
hi! link jsPrototype Yellow
hi! link jsOperator Orange
hi! link jsOperatorKeyword Red
hi! link jsClassKeyword Aqua
hi! link jsExtendsKeyword Aqua
hi! link jsExportDefault Aqua
hi! link jsTemplateBraces White
hi! link jsGlobalNodeObjects Blue
hi! link jsGlobalObjects Blue
hi! link jsFunction Aqua
hi! link jsFuncCall Blue
hi! link jsFuncParens White
hi! link jsParens White
hi! link jsNull Purple
hi! link jsUndefined Purple
hi! link jsClassDefinition Yellow
hi! link jsObjectKey GreenBold
hi! link typescriptReserved Aqua
hi! link typescriptLabel Aqua
hi! link typescriptFuncKeyword Aqua
hi! link typescriptIdentifier Orange
hi! link typescriptBraces White
hi! link typescriptEndColons White
hi! link typescriptDOMObjects White
hi! link typescriptAjaxMethods White
hi! link typescriptGlobalObjects White
hi! link typescriptParens White
hi! link typescriptOpSymbols Green
hi! link typescriptLogicSymbols Purple
hi! link typescriptInterpolation Aqua
hi! link typescriptHtmlElemProperties White
hi! link typescriptNull Purple
hi! link typescriptInterpolationDelimiter Aqua
hi! link typescriptDocSeeTag Comment
hi! link typescriptDocParam Comment
hi! link typescriptDocTags vimCommentTitle
hi! link jsxTagName Aqua
hi! link jsxComponentName Green
hi! link jsxCloseString LightGrey
hi! link jsxAttrib Yellow
hi! link jsxEqual Aqua
hi! link purescriptModuleKeyword Aqua
hi! link purescriptModuleName White
hi! link purescriptWhere Aqua
hi! link purescriptDelimiter White
hi! link purescriptType White
hi! link purescriptImportKeyword Aqua
hi! link purescriptHidingKeyword Aqua
hi! link purescriptAsKeyword Aqua
hi! link purescriptStructure Aqua
hi! link purescriptOperator Orange
hi! link purescriptTypeVar White
hi! link purescriptConstructor White
hi! link purescriptFunction White
hi! link purescriptConditional Orange
hi! link purescriptBacktick Orange
hi! link coffeeExtendedOp Orange
hi! link coffeeSpecialOp White
hi! link coffeeDotAccess Grey
hi! link coffeeCurly Orange
hi! link coffeeParen White
hi! link coffeeBracket Orange
hi! link javaAnnotation Blue
hi! link javaDocTags Aqua
hi! link javaParen White
hi! link javaParen1 White
hi! link javaParen2 White
hi! link javaParen3 White
hi! link javaParen4 White
hi! link javaParen5 White
hi! link javaOperator Orange
hi! link javaVarArg Green
hi! link javaCommentTitle vimCommentTitle
hi! link goDirective Aqua
hi! link goConstants Purple
hi! link goDeclaration Red
hi! link goDeclType Blue
hi! link goBuiltins Orange
hi! link rustSigil Orange
hi! link rustEscape Aqua
hi! link rustStringContinuation Aqua
hi! link rustEnum Aqua
hi! link rustStructure Aqua
hi! link rustDefault Aqua
hi! link rustModPathSep Grey
hi! link rustCommentLineDoc Comment
hi! link rubyStringDelimiter Green
hi! link rubyInterpolationDelimiter Aqua
hi! link luaIn Red
hi! link luaFunction Aqua
hi! link luaTable Orange
hi! link moonSpecialOp White
hi! link moonExtendedOp Orange
hi! link moonFunction White
hi! link moonObject Yellow
hi! link elixirStringDelimiter Green
hi! link elixirInterpolationDelimiter Aqua
hi! link elixirModuleDeclaration Yellow
hi! link elixirDocString Comment
hi! link clojureKeyword Blue
hi! link clojureCond Orange
hi! link clojureSpecial Orange
hi! link clojureDefine Orange
hi! link clojureFunc Yellow
hi! link clojureRepeat Yellow
hi! link clojureCharacter Aqua
hi! link clojureStringEscape Aqua
hi! link clojureException Red
hi! link clojureRegexp Aqua
hi! link clojureRegexpEscape Aqua
hi! link clojureAnonArg Yellow
hi! link clojureVariable Blue
hi! link clojureMacro Orange
hi! link clojureMeta Yellow
hi! link clojureDeref Yellow
hi! link clojureQuote Yellow
hi! link clojureUnquote Yellow
hi! link clojureRegexpMod clojureRegexpCharClass
hi! link clojureRegexpQuantifier clojureRegexpCharClass
hi! link clojureRegexpCharClass GreyBold
hi! link clojureParen White
hi! link scalaNameDefinition White
hi! link scalaCaseFollowing White
hi! link scalaCapitalWord White
hi! link scalaTypeExtension White
hi! link scalaKeyword Red
hi! link scalaKeywordModifier Red
hi! link scalaSpecial Aqua
hi! link scalaOperator Orange
hi! link scalaTypeDeclaration Yellow
hi! link scalaTypeTypePostDeclaration Yellow
hi! link scalaInstanceDeclaration White
hi! link scalaInterpolation Aqua
hi! link haskellType Blue
hi! link haskellIdentifier Aqua
hi! link haskellSeparator LightGrey
hi! link haskellDelimiter White
hi! link haskellOperators Green
hi! link haskellBacktick Orange
hi! link haskellStatement Purple
hi! link haskellConditional Purple
hi! link haskellLet Red
hi! link haskellDefault Red
hi! link haskellWhere Red
hi! link haskellDeclKeyword Orange
hi! link haskellDecl Orange
hi! link haskellDeriving Purple
hi! link haskellAssocType Aqua
hi! link haskellNumber Aqua
hi! link haskellForeignKeywords Green
hi! link haskellKeyword Red
hi! link haskellFloat Aqua
hi! link haskellInfix Purple
hi! link haskellRecursiveDo Purlpe
hi! link haskellQuotedType Red
hi! link haskellPreProc LightGrey
hi! link haskellTypeForall Red
hi! link haskellPatternKeyword Blue
hi! link haskellBottom RedBold
hi! link haskellTH AquaBold
hi! link haskellImportKeywords PurpleBold
hi! link haskellPragma RedBold
hi! link haskellQuote GreenBold
hi! link haskellShebang YellowBold
hi! link haskellLiquid PurpleBold
hi! link haskellQuasiQuoted BlueBold
hi! link haskellTypeRoles RedBold
hi! link perlStatementPackage PreProc
hi! link perlStatementInclude PreProc
hi! link perlStatementStorage StorageClass
hi! link perlStatementList StorageClass
hi! link perlVarSimpleMemberName Type
hi! link perlMethod Function
hi! link podCommand StorageClass
hi! link podCmdText Macro
hi! link podVerbatimLine String
hi! link jsonKeyword Green
hi! link jsonQuote Green
hi! link jsonBraces White
hi! link jsonString White
hi! link yamlKey Aqua
hi! link yamlConstant Purple
hi! link tomlTable Orange
hi! link tomlTableArray Orange
hi! link tomlKey White
hi! link mailHeader Blue
hi! link mailHeaderKey Blue
hi! link mailHeaderEmail Blue
hi! link mailSubject Blue
hi! link mailQuoted1 Aqua
hi! link mailQuoted2 Purple
hi! link mailQuoted3 Yellow
hi! link mailQuoted4 Green
hi! link mailQuoted5 Red
hi! link mailQuoted6 Orange
hi! link mailQuotedExp1 Aqua
hi! link mailQuotedExp2 Purple
hi! link mailQuotedExp3 Yellow
hi! link mailQuotedExp4 Green
hi! link mailQuotedExp5 Red
hi! link mailQuotedExp6 Orange
hi! link mailSignature White
hi! link mailURL Orange
hi! link mailEmail Orange
hi! link csBraces White
hi! link csEndColon White
hi! link csLogicSymbols Purple
hi! link csParens White
hi! link csOpSymbols Orange
hi! link csInterpolationDelimiter Aqua
hi! link csInterpolationFormat Aqua
hi! link csInterpolationAlignDel AquaBold
hi! link csInterpolationFormatDel AquaBold
hi! link shRange White
hi! link shTestOpr Purple
hi! link shOption Purple
hi! link bashStatement Orange
hi! link shOperator Orange
hi! link shQuote Green
hi! link shSet Orange
hi! link shSetList Blue
hi! link shSnglCase Orange
hi! link shVariable Blue
hi! link shCmdSubRegion Green
hi! link zshVariableDef Blue
hi! link zshSubst Orange
hi! link zshOptStart Orange
hi! link zshOption Aqua
hi! link zshFunction Green
hi! link vimNotation Orange
hi! link vimBracket Orange
hi! link vimMapModKey Purple
hi! link vimMapMod Purple
hi! link vimFuncSID LightGrey
hi! link vimSetSep LightGrey
hi! link vimSep LightGrey
hi! link vimContinue LightGrey
hi! link vimLet Orange
hi! link vimAutoCmd Orange
hi! link diffAdded Green
hi! link diffRemoved Red
hi! link diffChanged Yellow
hi! link diffOldFile Purple
hi! link diffNewFile Blue
hi! link diffFile Orange
hi! link diffLine Grey
hi! link diffIndexLine Aqua
hi! link helpHyperTextEntry Red
hi! link helpHyperTextJump Blue
hi! link helpSectionDelim Grey
hi! link helpExample Green
hi! link helpCommand Orange
hi! link helpHeadline Title
hi! link helpHeader Aqua
hi! link helpSpecial Yellow
hi! link plug2 Aqua
hi! link plugBracket Blue
hi! link plugName Green
hi! link plugH2 Purple
hi! link plugError Red
hi! link plugNotLoaded Grey
hi! link plugRelDate Grey
hi! link plugStar Blue
hi! link plugUpdate Aqua
hi! link plugMessage Purple
hi! link plugDeleted Grey
hi! link EasyMotionTarget Search
hi! link EasyMotionShade Comment
hi! link Sneak Search
hi! link SneakLabel Search
hi! link gitcommitSelectedFile Green
hi! link gitcommitDiscardedFile Red
let g:fzf_colors = {
      \ 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Green'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Aqua'],
      \ 'info':    ['fg', 'Aqua'],
      \ 'prompt':  ['fg', 'Orange'],
      \ 'pointer': ['fg', 'Blue'],
      \ 'marker':  ['fg', 'Yellow'],
      \ 'spinner': ['fg', 'Yellow'],
      \ 'header':  ['fg', 'Grey']
      \ }
hi! link CtrlPNoEntries Red
hi! link CtrlPPrtCursor Blue
if !exists('g:Lf_StlColorscheme')
  let g:Lf_StlColorscheme = 'gruvbox_material'
endif
hi! link StartifyBracket Grey
hi! link StartifyFile White
hi! link StartifyNumber Red
hi! link StartifyPath Green
hi! link StartifySlash Aqua
hi! link StartifySection Blue
hi! link StartifyHeader Orange
hi! link StartifySpecial Grey
hi! link StartifyFooter Grey
hi! link DirvishPathTail Aqua
hi! link DirvishArg Yellow
hi! link netrwDir Green
hi! link netrwClassify Green
hi! link netrwLink Grey
hi! link netrwSymLink White
hi! link netrwExe Yellow
hi! link netrwComment Grey
hi! link netrwList Aqua
hi! link netrwHelpCmd Blue
hi! link netrwCmdSep LightGrey
hi! link netrwVersion Orange
hi! link NERDTreeDir Green
hi! link NERDTreeDirSlash Aqua
hi! link NERDTreeOpenable Orange
hi! link NERDTreeClosable Orange
hi! link NERDTreeFile White
hi! link NERDTreeExecFile Yellow
hi! link NERDTreeUp Grey
hi! link NERDTreeCWD Aqua
hi! link NERDTreeHelp LightGrey
hi! link NERDTreeToggleOn Green
hi! link NERDTreeToggleOff Red
hi! link NERDTreeFlags Orange
hi! link NERDTreeLinkFile Grey
hi! link NERDTreeLinkTarget Green
hi! link TagbarFoldIcon Green
hi! link TagbarSignature Green
hi! link TagbarKind Red
hi! link TagbarScope Orange
hi! link TagbarNestedKind Aqua
hi! link TagbarVisibilityPrivate Red
hi! link TagbarVisibilityPublic Blue
hi! link ALEVirtualTextError Grey
hi! link ALEVirtualTextWarning Grey
hi! link ALEVirtualTextInfo Grey
hi! link ALEVirtualTextStyleError ALEVirtualTextError
hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
hi! link CocCodeLens Grey
hi! link CocErrorSign ALEErrorSign
hi! link CocWarningSign ALEWarningSign
hi! link CocInfoSign ALEInfoSign
hi! link CocErrorHighlight ALEError
hi! link CocWarningHighlight ALEWarning
hi! link CocInfoHighlight ALEInfo
hi! link CocWarningVirtualText ALEVirtualTextWarning
hi! link CocErrorVirtualText ALEVirtualTextError
hi! link CocInfoVirtualText ALEVirtualTextInfo
hi! link CocHintVirtualText ALEVirtualTextInfo
hi! link CocCodeLens ALEVirtualTextInfo
hi! link QuickmenuOption Green
hi! link QuickmenuNumber Red
hi! link QuickmenuBracket Grey
hi! link QuickmenuHelp Green
hi! link QuickmenuSpecial Purple
hi! link QuickmenuHeader Orange
hi! link UndotreeNode Orange
hi! link UndotreeNodeCurrent Red
hi! link UndotreeSeq Green
hi! link UndotreeNext Blue
hi! link UndotreeTimeStamp Grey
hi! link UndotreeHead Yellow
hi! link UndotreeBranch Yellow
hi! link UndotreeCurrent Aqua
hi! link UndotreeSavedSmall Purple

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#665c54', '#ea6962', '#a9b665', '#e78a4e',
        \ '#7daea3', '#d3869b', '#89b482', '#dfbf8e', '#928374', '#ea6962',
        \ '#a9b665', '#e3a84e', '#7daea3', '#d3869b', '#89b482', '#dfbf8e']
  if has('nvim')
    let g:terminal_color_0 = '#665c54'
    let g:terminal_color_1 = '#ea6962'
    let g:terminal_color_2 = '#a9b665'
    let g:terminal_color_3 = '#e78a4e'
    let g:terminal_color_4 = '#7daea3'
    let g:terminal_color_5 = '#d3869b'
    let g:terminal_color_6 = '#89b482'
    let g:terminal_color_7 = '#dfbf8e'
    let g:terminal_color_8 = '#928374'
    let g:terminal_color_9 = '#ea6962'
    let g:terminal_color_10 = '#a9b665'
    let g:terminal_color_11 = '#e3a84e'
    let g:terminal_color_12 = '#7daea3'
    let g:terminal_color_13 = '#d3869b'
    let g:terminal_color_14 = '#89b482'
    let g:terminal_color_15 = '#dfbf8e'
  endif
  hi White guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LightGrey guifg=#a89984 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Grey guifg=#928374 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Red guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Orange guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Yellow guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Green guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Aqua guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Blue guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Purple guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if get(g:, 'gruvbox_material_enable_bold', 0)
    hi WhiteBold guifg=#dfbf8e guibg=NONE guisp=NONE gui=bold cterm=bold
    hi LightGreyBold guifg=#a89984 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi GreyBold guifg=#928374 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi RedBold guifg=#ea6962 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi OrangeBold guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
    hi YellowBold guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
    hi GreenBold guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi AquaBold guifg=#89b482 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi BlueBold guifg=#7daea3 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi PurpleBold guifg=#d3869b guibg=NONE guisp=NONE gui=bold cterm=bold
  else
    hi WhiteBold guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi LightGreyBold guifg=#a89984 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi GreyBold guifg=#928374 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi RedBold guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi OrangeBold guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi YellowBold guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi GreenBold guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi AquaBold guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi BlueBold guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi PurpleBold guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  endif
  if get(g:, 'gruvbox_material_hard_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi DiffText guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi EndOfBuffer guifg=#1d2021 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#dfbf8e guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#dfbf8e guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
    hi DiffText guifg=NONE guibg=#1d2021 guisp=NONE gui=reverse cterm=reverse
    hi EndOfBuffer guifg=#1d2021 guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#e3a84e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#7c6f64 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#32361a guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#0d3138 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#3c1f1e guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ea6962 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ModeMsg guifg=#1d2021 guibg=#a89984 guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=#928374 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#928374 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=NONE guisp=NONE gui=bold,reverse ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Search guifg=NONE guibg=NONE guisp=NONE gui=reverse,underline ctermfg=NONE ctermbg=NONE cterm=reverse,underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#928374 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#dfbf8e guibg=#504945 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#504945 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#1d2021 guibg=#a89984 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#7c6f64 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi SpellBad guifg=#ea6962 guibg=NONE guisp=#ea6962 gui=italic,undercurl cterm=italic,undercurl
  hi SpellCap guifg=#7daea3 guibg=NONE guisp=#7daea3 gui=italic,undercurl cterm=italic,undercurl
  hi SpellLocal guifg=#89b482 guibg=NONE guisp=#89b482 gui=italic,undercurl cterm=italic,undercurl
  hi SpellRare guifg=#d3869b guibg=NONE guisp=#d3869b gui=italic,undercurl cterm=italic,undercurl
  hi StatusLine guifg=#dfbf8e guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#a89984 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineTerm guifg=#dfbf8e guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineTermNC guifg=#a89984 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#dfbf8e guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#dfbf8e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#1d2021 guibg=#a89984 guisp=NONE gui=bold cterm=bold
  hi VertSplit guifg=#665c54 guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu guifg=#1d2021 guibg=#a89984 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#928374 guibg=NONE guisp=NONE gui=bold,italic cterm=bold,italic
  hi CursorIM guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine guifg=NONE guibg=#665c54 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#dfbf8e guibg=#665c54 guisp=NONE gui=bold cterm=bold
  hi QuickFixLine guifg=#e3a84e guibg=#1d2021 guisp=NONE gui=reverse cterm=reverse
  hi Debug guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Conditional guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#ea6962 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#e3a84e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#e78a4e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#89b482 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#7daea3 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi Constant guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#d3869b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#7daea3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#dfbf8e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi SpellBad gui=undercurl cterm=undercurl
    hi SpellCap gui=undercurl cterm=undercurl
    hi SpellLocal gui=undercurl cterm=undercurl
    hi SpellRare gui=undercurl cterm=undercurl
    hi Todo gui=bold cterm=bold
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
  endif
  if get(g:, 'gruvbox_material_enable_bold', 0)
    hi Error guifg=#ea6962 guibg=#1d2021 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi Function guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  else
    hi Error guifg=#ea6962 guibg=#1d2021 guisp=NONE gui=reverse cterm=reverse
    hi Function guifg=#a9b665 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  endif
  hi markdownH1 guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH2 guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH3 guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH4 guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownUrl guifg=#d3869b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalicDelimiter guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi mkdURL guifg=#d3869b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdInlineURL guifg=#d3869b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdItalic guifg=#928374 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi htmlLink guifg=#a89984 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline guifg=NONE guibg=NONE guisp=NONE gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic,underline ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=italic,underline ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi vimCommentTitle guifg=#a89984 guibg=NONE guisp=NONE gui=bold,italic cterm=bold,italic
  hi helpURL guifg=#89b482 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi helpNote guifg=#d3869b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi plug1 guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi plugNumber guifg=#e3a84e guibg=NONE guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi markdownItalic gui=NONE cterm=NONE
    hi markdownItalicDelimiter gui=NONE cterm=NONE
    hi mkdItalic gui=NONE cterm=NONE
    hi htmlBoldItalic gui=bold cterm=bold
    hi htmlBoldUnderlineItalic gui=bold,underline cterm=bold,underline
    hi htmlUnderlineItalic gui=underline cterm=underline
    hi htmlItalic gui=NONE cterm=NONE
    hi vimCommentTitle gui=bold cterm=bold
  endif
  if get(g:, 'indent_guides_auto_colors', 0)
    if get(g:, 'gruvbox_material_hard_invert_indent_guides', 0)
      hi IndentGuidesOdd guifg=#1d2021 guibg=#504945 guisp=NONE gui=reverse cterm=reverse
      hi IndentGuidesEven guifg=#1d2021 guibg=#3c3836 guisp=NONE gui=reverse cterm=reverse
    else
      hi IndentGuidesOdd guifg=#1d2021 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
      hi IndentGuidesEven guifg=#1d2021 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
    endif
  endif
  if !exists('g:indentLine_color_term')
    let g:indentLine_color_term = 239
  endif
  if !exists('g:indentLine_color_gui')
    let g:indentLine_color_gui = '#504945'
  endif
  " Rainbow Parentheses
  if !exists('g:rbpt_colorpairs')
    let g:rbpt_colorpairs = [['blue', '#7daea3'], ['magenta', '#d3869b'],
          \ ['red', '#ea6962'], ['208', '#e78a4e']]
  endif

  let g:rainbow_guifgs = [ '#e78a4e', '#ea6962', '#d3869b', '#7daea3' ]
  let g:rainbow_ctermfgs = [ '208', 'red', 'magenta', 'blue' ]

  if !exists('g:rainbow_conf')
    let g:rainbow_conf = {}
  endif
  if !has_key(g:rainbow_conf, 'guifgs')
    let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
  endif
  if !has_key(g:rainbow_conf, 'ctermfgs')
    let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
  endif

  let g:niji_dark_colours = g:rbpt_colorpairs
  let g:niji_light_colours = g:rbpt_colorpairs
  hi GitGutterAdd guifg=#a9b665 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#ea6962 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#d3869b guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignAdd guifg=#a9b665 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignChange guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignDelete guifg=#ea6962 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SyntasticError guifg=NONE guibg=NONE guisp=#ea6962 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SyntasticWarning guifg=NONE guibg=NONE guisp=#e3a84e gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SyntasticErrorSign guifg=#ea6962 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SyntasticWarningSign guifg=#e3a84e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignatureMarkText guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi SignatureMarkerText guifg=#d3869b guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ShowMarksHLl guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ShowMarksHLu guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ShowMarksHLo guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ShowMarksHLm guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi CtrlPMatch guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi CtrlPPrtBase guifg=#504945 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CtrlPLinePre guifg=#504945 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CtrlPMode1 guifg=#7daea3 guibg=#504945 guisp=NONE gui=bold cterm=bold
  hi CtrlPMode2 guifg=#1d2021 guibg=#7daea3 guisp=NONE gui=bold cterm=bold
  hi CtrlPStats guifg=#a89984 guibg=#504945 guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match0 guifg=#a9b665 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match1 guifg=#89b482 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match2 guifg=#7daea3 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match3 guifg=#d3869b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match4 guifg=#e78a4e guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_matchRefine guifg=#ea6962 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi StartifyFooter guifg=#928374 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  let g:vimshell_escape_colors = [
        \ '#7c6f64', '#ea6962', '#a9b665', '#e3a84e',
        \ '#7daea3', '#d3869b', '#89b482', '#a89984',
        \ '#1d2021', '#ea6962', '#a9b665', '#e78a4e',
        \ '#7daea3', '#d3869b', '#89b482', '#dfbf8e'
        \ ]
  hi BufTabLineCurrent guifg=#1d2021 guibg=#a89984 guisp=NONE gui=NONE cterm=NONE
  hi BufTabLineActive guifg=#a89984 guibg=#504945 guisp=NONE gui=NONE cterm=NONE
  hi BufTabLineHidden guifg=#7c6f64 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi BufTabLineFill guifg=#1d2021 guibg=#1d2021 guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=NONE guisp=#ea6962 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEWarning guifg=NONE guibg=NONE guisp=#ea6962 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEInfo guifg=NONE guibg=NONE guisp=#7daea3 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEErrorSign guifg=#ea6962 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#e3a84e guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#7daea3 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi multiple_cursors_cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual guifg=NONE guibg=#504945 guisp=NONE gui=NONE cterm=NONE
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign guifg=#89b482 guibg=#3c3836 guisp=NONE gui=NONE cterm=NONE
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig guifg=#d3869b guibg=NONE guisp=NONE gui=bold cterm=bold
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi White ctermfg=223 ctermbg=NONE cterm=NONE
  hi LightGrey ctermfg=246 ctermbg=NONE cterm=NONE
  hi Grey ctermfg=245 ctermbg=NONE cterm=NONE
  hi Red ctermfg=167 ctermbg=NONE cterm=NONE
  hi Orange ctermfg=208 ctermbg=NONE cterm=NONE
  hi Yellow ctermfg=214 ctermbg=NONE cterm=NONE
  hi Green ctermfg=142 ctermbg=NONE cterm=NONE
  hi Aqua ctermfg=108 ctermbg=NONE cterm=NONE
  hi Blue ctermfg=109 ctermbg=NONE cterm=NONE
  hi Purple ctermfg=175 ctermbg=NONE cterm=NONE
  if get(g:, 'gruvbox_material_enable_bold', 0)
    hi WhiteBold ctermfg=223 ctermbg=NONE cterm=bold
    hi LightGreyBold ctermfg=246 ctermbg=NONE cterm=bold
    hi GreyBold ctermfg=245 ctermbg=NONE cterm=bold
    hi RedBold ctermfg=167 ctermbg=NONE cterm=bold
    hi OrangeBold ctermfg=208 ctermbg=NONE cterm=bold
    hi YellowBold ctermfg=214 ctermbg=NONE cterm=bold
    hi GreenBold ctermfg=142 ctermbg=NONE cterm=bold
    hi AquaBold ctermfg=108 ctermbg=NONE cterm=bold
    hi BlueBold ctermfg=109 ctermbg=NONE cterm=bold
    hi PurpleBold ctermfg=175 ctermbg=NONE cterm=bold
  else
    hi WhiteBold ctermfg=223 ctermbg=NONE cterm=NONE
    hi LightGreyBold ctermfg=246 ctermbg=NONE cterm=NONE
    hi GreyBold ctermfg=245 ctermbg=NONE cterm=NONE
    hi RedBold ctermfg=167 ctermbg=NONE cterm=NONE
    hi OrangeBold ctermfg=208 ctermbg=NONE cterm=NONE
    hi YellowBold ctermfg=214 ctermbg=NONE cterm=NONE
    hi GreenBold ctermfg=142 ctermbg=NONE cterm=NONE
    hi AquaBold ctermfg=108 ctermbg=NONE cterm=NONE
    hi BlueBold ctermfg=109 ctermbg=NONE cterm=NONE
    hi PurpleBold ctermfg=175 ctermbg=NONE cterm=NONE
  endif
  if get(g:, 'gruvbox_material_hard_transp_bg', 0)
    hi Normal ctermfg=223 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=223 ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=NONE cterm=reverse
    hi EndOfBuffer ctermfg=234 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=223 ctermbg=234 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=223 ctermbg=234 cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=234 cterm=reverse
    hi EndOfBuffer ctermfg=234 ctermbg=234 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi Conceal ctermfg=109 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLineNr ctermfg=214 ctermbg=237 cterm=NONE
  hi LineNr ctermfg=243 ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=52 cterm=NONE
  hi Directory ctermfg=142 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=214 ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=234 ctermbg=246 cterm=bold
  hi MoreMsg ctermfg=214 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=245 ctermbg=237 cterm=NONE
  hi Folded ctermfg=245 ctermbg=237 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Search ctermfg=NONE ctermbg=NONE cterm=reverse,underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=245 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=223 ctermbg=239 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=239 cterm=NONE
  hi PmenuSel ctermfg=234 ctermbg=246 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=243 cterm=NONE
  hi Question ctermfg=208 ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=167 ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=109 ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=108 ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=175 ctermbg=NONE cterm=italic,underline
  hi StatusLine ctermfg=223 ctermbg=241 cterm=NONE
  hi StatusLineNC ctermfg=246 ctermbg=237 cterm=NONE
  hi StatusLineTerm ctermfg=223 ctermbg=241 cterm=NONE
  hi StatusLineTermNC ctermfg=246 ctermbg=237 cterm=NONE
  hi TabLine ctermfg=223 ctermbg=241 cterm=NONE
  hi TabLineFill ctermfg=223 ctermbg=237 cterm=NONE
  hi TabLineSel ctermfg=234 ctermbg=246 cterm=bold
  hi VertSplit ctermfg=241 ctermbg=234 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu ctermfg=234 ctermbg=246 cterm=NONE
  hi Todo ctermfg=245 ctermbg=NONE cterm=bold,italic
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=241 cterm=NONE
  hi ToolbarButton ctermfg=223 ctermbg=241 cterm=bold
  hi QuickFixLine ctermfg=214 ctermbg=234 cterm=reverse
  hi Debug ctermfg=208 ctermbg=NONE cterm=NONE
  hi Title ctermfg=142 ctermbg=NONE cterm=bold
  hi Conditional ctermfg=167 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=167 ctermbg=NONE cterm=NONE
  hi Label ctermfg=167 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=167 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=214 ctermbg=NONE cterm=NONE
  hi Type ctermfg=214 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=208 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=223 ctermbg=NONE cterm=NONE
  hi Special ctermfg=208 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=208 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=208 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=208 ctermbg=NONE cterm=NONE
  hi String ctermfg=142 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=108 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=108 ctermbg=NONE cterm=NONE
  hi Define ctermfg=108 ctermbg=NONE cterm=NONE
  hi Include ctermfg=108 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=108 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=108 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=109 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=109 ctermbg=NONE cterm=underline
  hi Constant ctermfg=175 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=175 ctermbg=NONE cterm=NONE
  hi Character ctermfg=175 ctermbg=NONE cterm=NONE
  hi Number ctermfg=175 ctermbg=NONE cterm=NONE
  hi Float ctermfg=175 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=109 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=245 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=245 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=223 ctermbg=NONE cterm=NONE
  if !s:italics
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi Todo cterm=bold
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  if get(g:, 'gruvbox_material_enable_bold', 0)
    hi Error ctermfg=167 ctermbg=234 cterm=bold,reverse
    hi Function ctermfg=142 ctermbg=NONE cterm=bold
  else
    hi Error ctermfg=167 ctermbg=234 cterm=reverse
    hi Function ctermfg=142 ctermbg=NONE cterm=NONE
  endif
  hi markdownH1 ctermfg=142 ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=142 ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=214 ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=214 ctermbg=NONE cterm=bold
  hi markdownUrl ctermfg=175 ctermbg=NONE cterm=underline
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalicDelimiter ctermfg=245 ctermbg=NONE cterm=italic
  hi mkdURL ctermfg=175 ctermbg=NONE cterm=underline
  hi mkdInlineURL ctermfg=175 ctermbg=NONE cterm=underline
  hi mkdItalic ctermfg=245 ctermbg=NONE cterm=italic
  hi htmlLink ctermfg=246 ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi vimCommentTitle ctermfg=246 ctermbg=NONE cterm=bold,italic
  hi helpURL ctermfg=108 ctermbg=NONE cterm=underline
  hi helpNote ctermfg=175 ctermbg=NONE cterm=bold
  hi plug1 ctermfg=208 ctermbg=NONE cterm=bold
  hi plugNumber ctermfg=214 ctermbg=NONE cterm=bold
  if !s:italics
    hi markdownItalic cterm=NONE
    hi markdownItalicDelimiter cterm=NONE
    hi mkdItalic cterm=NONE
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlUnderlineItalic cterm=underline
    hi htmlItalic cterm=NONE
    hi vimCommentTitle cterm=bold
  endif
  if get(g:, 'indent_guides_auto_colors', 0)
    if get(g:, 'gruvbox_material_hard_invert_indent_guides', 0)
      hi IndentGuidesOdd ctermfg=234 ctermbg=239 cterm=reverse
      hi IndentGuidesEven ctermfg=234 ctermbg=237 cterm=reverse
    else
      hi IndentGuidesOdd ctermfg=234 ctermbg=239 cterm=NONE
      hi IndentGuidesEven ctermfg=234 ctermbg=237 cterm=NONE
    endif
  endif
  if !exists('g:indentLine_color_term')
    let g:indentLine_color_term = 239
  endif
  if !exists('g:indentLine_color_gui')
    let g:indentLine_color_gui = '#504945'
  endif
  " Rainbow Parentheses
  if !exists('g:rbpt_colorpairs')
    let g:rbpt_colorpairs = [['blue', '#7daea3'], ['magenta', '#d3869b'],
          \ ['red', '#ea6962'], ['208', '#e78a4e']]
  endif

  let g:rainbow_guifgs = [ '#e78a4e', '#ea6962', '#d3869b', '#7daea3' ]
  let g:rainbow_ctermfgs = [ '208', 'red', 'magenta', 'blue' ]

  if !exists('g:rainbow_conf')
    let g:rainbow_conf = {}
  endif
  if !has_key(g:rainbow_conf, 'guifgs')
    let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
  endif
  if !has_key(g:rainbow_conf, 'ctermfgs')
    let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
  endif

  let g:niji_dark_colours = g:rbpt_colorpairs
  let g:niji_light_colours = g:rbpt_colorpairs
  hi GitGutterAdd ctermfg=142 ctermbg=237 cterm=NONE
  hi GitGutterChange ctermfg=109 ctermbg=237 cterm=NONE
  hi GitGutterDelete ctermfg=167 ctermbg=237 cterm=NONE
  hi GitGutterChangeDelete ctermfg=175 ctermbg=237 cterm=NONE
  hi SignifySignAdd ctermfg=142 ctermbg=237 cterm=NONE
  hi SignifySignChange ctermfg=109 ctermbg=237 cterm=NONE
  hi SignifySignDelete ctermfg=167 ctermbg=237 cterm=NONE
  hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticErrorSign ctermfg=167 ctermbg=237 cterm=NONE
  hi SyntasticWarningSign ctermfg=214 ctermbg=237 cterm=NONE
  hi SignatureMarkText ctermfg=109 ctermbg=237 cterm=NONE
  hi SignatureMarkerText ctermfg=175 ctermbg=237 cterm=NONE
  hi ShowMarksHLl ctermfg=109 ctermbg=237 cterm=NONE
  hi ShowMarksHLu ctermfg=109 ctermbg=237 cterm=NONE
  hi ShowMarksHLo ctermfg=109 ctermbg=237 cterm=NONE
  hi ShowMarksHLm ctermfg=109 ctermbg=237 cterm=NONE
  hi CtrlPMatch ctermfg=142 ctermbg=NONE cterm=bold
  hi CtrlPPrtBase ctermfg=239 ctermbg=NONE cterm=NONE
  hi CtrlPLinePre ctermfg=239 ctermbg=NONE cterm=NONE
  hi CtrlPMode1 ctermfg=109 ctermbg=239 cterm=bold
  hi CtrlPMode2 ctermfg=234 ctermbg=109 cterm=bold
  hi CtrlPStats ctermfg=246 ctermbg=239 cterm=bold
  hi Lf_hl_match ctermfg=142 ctermbg=NONE cterm=bold
  hi Lf_hl_match0 ctermfg=142 ctermbg=NONE cterm=bold
  hi Lf_hl_match1 ctermfg=108 ctermbg=NONE cterm=bold
  hi Lf_hl_match2 ctermfg=109 ctermbg=NONE cterm=bold
  hi Lf_hl_match3 ctermfg=175 ctermbg=NONE cterm=bold
  hi Lf_hl_match4 ctermfg=208 ctermbg=NONE cterm=bold
  hi Lf_hl_matchRefine ctermfg=167 ctermbg=NONE cterm=bold
  hi StartifyFooter ctermfg=245 ctermbg=NONE cterm=NONE
  let g:vimshell_escape_colors = [
        \ '#7c6f64', '#ea6962', '#a9b665', '#e3a84e',
        \ '#7daea3', '#d3869b', '#89b482', '#a89984',
        \ '#1d2021', '#ea6962', '#a9b665', '#e78a4e',
        \ '#7daea3', '#d3869b', '#89b482', '#dfbf8e'
        \ ]
  hi BufTabLineCurrent ctermfg=234 ctermbg=246 cterm=NONE
  hi BufTabLineActive ctermfg=246 ctermbg=239 cterm=NONE
  hi BufTabLineHidden ctermfg=243 ctermbg=237 cterm=NONE
  hi BufTabLineFill ctermfg=234 ctermbg=234 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=167 ctermbg=237 cterm=NONE
  hi ALEWarningSign ctermfg=214 ctermbg=237 cterm=NONE
  hi ALEInfoSign ctermfg=109 ctermbg=237 cterm=NONE
  hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual ctermfg=NONE ctermbg=239 cterm=NONE
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign ctermfg=108 ctermbg=237 cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig ctermfg=175 ctermbg=NONE cterm=bold
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'gruvbox_material_hard_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=NONE cterm=reverse
    hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=Black cterm=reverse
    hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi lCursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=Yellow ctermbg=DarkGrey cterm=NONE
  hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=Black ctermbg=LightGrey cterm=bold
  hi MoreMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=NONE cterm=bold,reverse
  hi Search ctermfg=NONE ctermbg=NONE cterm=reverse,underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Question ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=Blue ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=Cyan ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=italic,underline
  hi StatusLine ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi StatusLineTerm ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi StatusLineTermNC ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi TabLine ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=LightGrey cterm=bold
  hi VertSplit ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Todo ctermfg=Grey ctermbg=NONE cterm=bold,italic
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=DarkGrey cterm=bold
  hi QuickFixLine ctermfg=Yellow ctermbg=Black cterm=reverse
  hi Debug ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Title ctermfg=Green ctermbg=NONE cterm=bold
  hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Red ctermbg=NONE cterm=NONE
  hi Label ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Tag ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Macro ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Define ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Include ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
  hi Constant ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Character ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Float ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  if !s:italics
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi Todo cterm=bold
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  if get(g:, 'gruvbox_material_enable_bold', 0)
    hi Error ctermfg=Red ctermbg=Black cterm=bold,reverse
    hi Function ctermfg=Green ctermbg=NONE cterm=bold
  else
    hi Error ctermfg=Red ctermbg=Black cterm=reverse
    hi Function ctermfg=Green ctermbg=NONE cterm=NONE
  endif
  hi markdownH1 ctermfg=Green ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=Green ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi markdownUrl ctermfg=Magenta ctermbg=NONE cterm=underline
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalicDelimiter ctermfg=Grey ctermbg=NONE cterm=italic
  hi mkdURL ctermfg=Magenta ctermbg=NONE cterm=underline
  hi mkdInlineURL ctermfg=Magenta ctermbg=NONE cterm=underline
  hi mkdItalic ctermfg=Grey ctermbg=NONE cterm=italic
  hi htmlLink ctermfg=LightGrey ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi vimCommentTitle ctermfg=LightGrey ctermbg=NONE cterm=bold,italic
  hi helpURL ctermfg=Cyan ctermbg=NONE cterm=underline
  hi helpNote ctermfg=Magenta ctermbg=NONE cterm=bold
  hi plug1 ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi plugNumber ctermfg=Yellow ctermbg=NONE cterm=bold
  if !s:italics
    hi markdownItalic cterm=NONE
    hi markdownItalicDelimiter cterm=NONE
    hi mkdItalic cterm=NONE
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlUnderlineItalic cterm=underline
    hi htmlItalic cterm=NONE
    hi vimCommentTitle cterm=bold
  endif
  if get(g:, 'indent_guides_auto_colors', 0)
    if get(g:, 'gruvbox_material_hard_invert_indent_guides', 0)
      hi IndentGuidesOdd ctermfg=Black ctermbg=DarkGrey cterm=reverse
      hi IndentGuidesEven ctermfg=Black ctermbg=DarkGrey cterm=reverse
    else
      hi IndentGuidesOdd ctermfg=Black ctermbg=DarkGrey cterm=NONE
      hi IndentGuidesEven ctermfg=Black ctermbg=DarkGrey cterm=NONE
    endif
  endif
  if !exists('g:indentLine_color_term')
    let g:indentLine_color_term = 239
  endif
  if !exists('g:indentLine_color_gui')
    let g:indentLine_color_gui = '#504945'
  endif
  " Rainbow Parentheses
  if !exists('g:rbpt_colorpairs')
    let g:rbpt_colorpairs = [['blue', '#7daea3'], ['magenta', '#d3869b'],
          \ ['red', '#ea6962'], ['208', '#e78a4e']]
  endif

  let g:rainbow_guifgs = [ '#e78a4e', '#ea6962', '#d3869b', '#7daea3' ]
  let g:rainbow_ctermfgs = [ '208', 'red', 'magenta', 'blue' ]

  if !exists('g:rainbow_conf')
    let g:rainbow_conf = {}
  endif
  if !has_key(g:rainbow_conf, 'guifgs')
    let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
  endif
  if !has_key(g:rainbow_conf, 'ctermfgs')
    let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
  endif

  let g:niji_dark_colours = g:rbpt_colorpairs
  let g:niji_light_colours = g:rbpt_colorpairs
  hi GitGutterAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi GitGutterChange ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi GitGutterDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi GitGutterChangeDelete ctermfg=Magenta ctermbg=DarkGrey cterm=NONE
  hi SignifySignAdd ctermfg=Green ctermbg=DarkGrey cterm=NONE
  hi SignifySignChange ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi SignifySignDelete ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticErrorSign ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi SyntasticWarningSign ctermfg=Yellow ctermbg=DarkGrey cterm=NONE
  hi SignatureMarkText ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi SignatureMarkerText ctermfg=Magenta ctermbg=DarkGrey cterm=NONE
  hi ShowMarksHLl ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi ShowMarksHLu ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi ShowMarksHLo ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi ShowMarksHLm ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi CtrlPMatch ctermfg=Green ctermbg=NONE cterm=bold
  hi CtrlPPrtBase ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi CtrlPLinePre ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi CtrlPMode1 ctermfg=Blue ctermbg=DarkGrey cterm=bold
  hi CtrlPMode2 ctermfg=Black ctermbg=Blue cterm=bold
  hi CtrlPStats ctermfg=LightGrey ctermbg=DarkGrey cterm=bold
  hi Lf_hl_match ctermfg=Green ctermbg=NONE cterm=bold
  hi Lf_hl_match0 ctermfg=Green ctermbg=NONE cterm=bold
  hi Lf_hl_match1 ctermfg=Cyan ctermbg=NONE cterm=bold
  hi Lf_hl_match2 ctermfg=Blue ctermbg=NONE cterm=bold
  hi Lf_hl_match3 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi Lf_hl_match4 ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi Lf_hl_matchRefine ctermfg=Red ctermbg=NONE cterm=bold
  hi StartifyFooter ctermfg=Grey ctermbg=NONE cterm=NONE
  let g:vimshell_escape_colors = [
        \ '#7c6f64', '#ea6962', '#a9b665', '#e3a84e',
        \ '#7daea3', '#d3869b', '#89b482', '#a89984',
        \ '#1d2021', '#ea6962', '#a9b665', '#e78a4e',
        \ '#7daea3', '#d3869b', '#89b482', '#dfbf8e'
        \ ]
  hi BufTabLineCurrent ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi BufTabLineActive ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi BufTabLineHidden ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  hi BufTabLineFill ctermfg=Black ctermbg=Black cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi ALEWarningSign ctermfg=Yellow ctermbg=DarkGrey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=DarkGrey cterm=NONE
  hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHintSign ctermfg=Cyan ctermbg=DarkGrey cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig ctermfg=Magenta ctermbg=NONE cterm=bold
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background:             dark
" Color: dark0            #1d2021         234             Black
" Color: dark1            #3c3836         237             DarkGrey
" Color: dark2            #504945         239             DarkGrey
" Color: dark3            #665c54         241             DarkGrey
" Color: dark4            #7c6f64         243             DarkGrey
" Color: grey             #928374         245             Grey
" Color: lightgrey        #a89984         246             LightGrey
" Color: light            #dfbf8e         223             White
" Color: red              #ea6962         167             Red
" Color: orange           #e78a4e         208             DarkYellow
" Color: yellow           #e3a84e         214             Yellow
" Color: green            #a9b665         142             Green
" Color: aqua             #89b482         108             Cyan
" Color: blue             #7daea3         109             Blue
" Color: purple           #d3869b         175             Magenta
" Color: darkgreen        #32361a         ~               DarkGreen
" Color: darkred          #3c1f1e         ~               DarkRed
" Color: darkblue         #0d3138         ~               DarkBlue
" Term colors: dark3 red green orange blue purple aqua light
" Term colors: grey red green yellow blue purple aqua light
" vim: et ts=2 sw=2
